language:  ruby
rvm:
  - 2.4.1
  - ruby-head

bundler_args: --without production

script:
  - bundle exec rake db:migrate RAILS_ENV=test --trace
  - bundle exec rake db:test:prepare
  - bundle exec rake